### ISSUE TITLE
generated column 'variant_listing_config' in table 'product'

### ISSUE THREAD

**Issue by rawdlite** [kellerkinderDE/shopware6-database-dump#7]
hi,

first off thank you a lot for providing this script.
I want to use it to sync a production instance with a development instance under dockware.

SW6 is 6.4.17.2 
Source DB is mysqld Ver 10.3.37-MariaDB-0ubuntu0.20.04.1, mysqldump  Ver 10.19 Distrib 10.3.37-MariaDB
Target DB is mysqld  Ver 5.7.40-0ubuntu0.18.04.1. (dockware)
Dump was created with --gdpr option.
On import i get error:
`The value specified for generated column 'variant_listing_config' in table 'product' is not allowed`

On removing the product table inserts from the dump, the import finished without errors.
Yet users table was empty (had to create new admin user on console)

I suspect MariadDB is not supported by this script? 
MariaDB 10.3.22 or higher is officially supported by shopware, so it should be 'Standard DB' ?

Could we extend script to write product table into temporary table without column  variant_listing_config and dump that table instead? Or maybe a view?

Or maybe mysqldump version is to blame? 

Please advise howto proceed.

TIA 

tom

**Comment by kleinmann** [comment]
This is related to an incompatibility between MariaDB and MySQL for generated columns, see the [MySQL issue for that](https://bugs.mysql.com/bug.php?id=79148). I recommend not switching between the two, if possible.

You could also try generating the dump with mysqldump from MySQL instead of MariaDB's mysqldump.

Unfortunately, hard to fix on our side.

**Comment by rawdlite** [comment]
Thank you for your prompt reply.

> incompatibility between MariaDB and MySQL for generated columns

That would have been great to have known before. Switching to another DB Engine on production without being able to do a proper dump will be tricky. 

>  try generating the dump with mysqldump from MySQL instead of MariaDB's mysqldump

will try that. Thanks.
